resources:
  - ../../base

nameSuffix: -prod

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: app
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: app

configMapGenerator:
  - name: app-config
    envs:
      - config.env

secretGenerator:
  - name: app-secret
    literals:
      - DB_PASSWORD=prod123

images:
  - name: app
    newName: 192.168.0.106:5000/app
    newTag: latest
